name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "tier-2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Call `AudioDevice.shared`
        2. Run FFT with size 4096
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code that reproduces the issue
      render: swift

  - type: dropdown
    id: module
    attributes:
      label: Module
      options:
        - MetalAudioKit
        - MetalDSP
        - MetalNN
        - Multiple/Unknown
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: MetalAudio version or commit hash
      placeholder: "1.0.0 or abc123"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - macOS 13
        - macOS 14
        - macOS 15
        - iOS 16
        - iOS 17
        - iOS 18
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: I can reproduce this on the latest main branch
          required: false
